language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true
  - openssl genrsa -out app/var/jwt/private.pem -aes256 -passout pass:thisisfortests 4096
  - openssl rsa -pubout -in app/var/jwt/private.pem -out app/var/jwt/public.pem -passin pass:thisisfortests
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - touch app/config/parameters_test.yml

install:
  - composer install --prefer-dist

before_script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
