# Helper service configurations
#
# This file contains helper service specified configurations.
services:
    app.services.helper.roles:
        class: App\Services\Helper\Roles
        arguments: [ '%security.role_hierarchy.roles%' ]

    app.services.helper.search_term:
        class: App\Services\Helper\SearchTerm

    app.services.response_logger:
        class: App\Services\ResponseLogger
        arguments: [ '@logger', '@app.services.rest.request_log' ]
