services:
    app.controller.auth:
        class:      App\Controller\AuthController
        arguments:  [ '@security.token_storage', '@jms_serializer' ]

    app.controller.author:
        class:      App\Controller\AuthorController
        arguments:  [ '@app.services.rest.author', '@app.services.rest.helper.response' ]

    app.controller.book:
        class:      App\Controller\BookController
        arguments:  [ '@app.services.rest.book', '@app.services.rest.helper.response' ]
